workspace '../Kitz.xcworkspace'
xcodeproj 'Kitz.xcodeproj'

platform :ios, '8.0'

use_frameworks!

target :'Kitz' do

	pod 'Appz',            :git => 'https://github.com/SwiftKitz/Appz.git'
	pod 'Datez',           :git => 'https://github.com/SwiftKitz/Datez.git'
	pod 'Notificationz',   :git => 'https://github.com/SwiftKitz/Notificationz.git'
	pod 'Storez',          :git => 'https://github.com/SwiftKitz/Storez.git'
end
